### ISSUE TITLE
Cannot find loaded worlds

### ISSUE THREAD

**Issue by stifflered** [RoboMWM/MidnightPortal#1]
Got an error when loading the plugin. Running latest build (489) of PaperSpigot 1.13.2 and the latest versions of WorldGuard and Multiverse.

This happens on server load:

```
[01:46:36] [Server thread/INFO]: [MidnightPortal] Enabling MidnightPortal v1.0
[01:46:36] [Server thread/WARN]: [MidnightPortal] challenge or TheFlow is not a valid/loaded world. 
```

This is my config:
```
portalFrameMaterial: QUARTZ_BLOCK
enabledWorlds:
  challenge:
    TheFlow: 10.0
  TheFlow:
    challenge: 0.1
```

These are the two worlds in Multiverse. They are loaded there and in WorldGuard since I can enter them and modify them as needed.

```
TheFlow:
    ==: MVWorld
    hidden: 'false'
    alias: TheFlow
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '10.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: HARD
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 71.0
      z: 0.0
      pitch: -1.950006
      yaw: -3.7500005
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '7414836039109396892'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
  challenge:
    ==: MVWorld
    hidden: 'false'
    alias: challenge
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'false'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -13.526359210147286
      y: 71.0
      z: 41.289882654289045
      pitch: 9.600014
      yaw: -93.15247
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '2515973426658598677'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
```
